# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/exynos7885-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter a7y18lte,$(TARGET_DEVICE)),)

endif
